// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function BulkDeleteDocuments(arg1:string,arg2:Array<string>):Promise<void>;

export function ConnectToDatabase(arg1:database.ConnectionConfig):Promise<void>;

export function DisconnectFirestore():Promise<void>;

export function GetCollection(arg1:string,arg2:database.QueryParams):Promise<database.QueryResult>;

export function GetDocument(arg1:string):Promise<database.DocumentResult>;

export function Greet(arg1:string):Promise<string>;

export function IsDatabaseConnected():Promise<boolean>;

export function ListCollections():Promise<Array<database.CollectionInfo>>;

export function QueryCollection(arg1:string,arg2:string,arg3:string,arg4:any,arg5:database.QueryParams):Promise<database.QueryResult>;
