// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkDeleteDocuments(arg1, arg2) {
  return window['go']['main']['App']['BulkDeleteDocuments'](arg1, arg2);
}

export function ConnectToDatabase(arg1) {
  return window['go']['main']['App']['ConnectToDatabase'](arg1);
}

export function DisconnectFirestore() {
  return window['go']['main']['App']['DisconnectFirestore']();
}

export function GetCollection(arg1, arg2) {
  return window['go']['main']['App']['GetCollection'](arg1, arg2);
}

export function GetDatabaseConnectionStatus() {
  return window['go']['main']['App']['GetDatabaseConnectionStatus']();
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsDatabaseConnected() {
  return window['go']['main']['App']['IsDatabaseConnected']();
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}
